config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/', to: 'timecard#index', as: :timecard
  post '/timecard', to: 'timecard#create', as: :timecard_punch

  get '/sign_up', to: 'sign_up#index', as: :sign_up
  post '/sign_up', to: 'sign_up#create'

  get '/login', to: 'login#index', as: :login
  post '/login', to: 'login#create'
  get '/logout', to: 'login#delete', as: :logout

  get '/admin', to: 'admin#index', as: :admin
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/timecard.rb
# frozen_string_literal: true

class Timecard < ApplicationRecord
  belongs_to :user

  validates :clocked_in_at, presence: true
  validate :validate_clocked_out_at

  scope :active, -> { where(clocked_out_at: nil) }
  scope :complete, -> { where.not(clocked_out_at: nil) }
  scope :recent, -> { order(updated_at: :desc) }

  def clock_out!(time: Time.zone.now)
    raise ArgumentError, 'Already has a clocked_out_at' if clocked_out_at.present?

    update!(clocked_out_at: time)
  end

  private

  def validate_clocked_out_at
    return true if clocked_out_at.blank?
    return true if clocked_out_at > clocked_in_at

    errors.add(:clocked_out_at, 'must be later than clock in')
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :password

  has_many :timecards

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, format: /.+@.+\..+/i
  validates :password, length: { minimum: 6 }, on: :create

  before_save :encrypt_password

  def self.sign_in(email:, password:)
    user = find_by(email: email)
    return unless user
    return if user.password_hash != BCrypt::Engine.hash_secret(password, user.password_salt)

    user
  end

  def active_timecard
    timecards.active.first
  end

  def punch_clock!
    if active_timecard
      active_timecard.clock_out!
    else
      timecards.create(clocked_in_at: Time.zone.now)
    end
  end

  private

  def encrypt_password
    return if password.blank?

    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end
end

app/controllers/admin_controller.rb
# frozen_string_literal: true

class AdminController < ApplicationController
  before_action :must_be_admin

  def index
    @timecards = Timecard.eager_load(:user).all # TODO: Paginate me
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  def must_be_admin
    return if signed_in? && current_user.admin?

    redirect_to '/'
  end

  def must_be_signed_in
    return if signed_in?

    redirect_to login_path
  end

  def must_be_signed_out
    return if signed_out?

    redirect_to '/'
  end

  def signed_in?
    current_user.present?
  end

  def signed_out?
    !signed_in?
  end

  def sign_in(user:)
    session[:user_id] = user.id
  end
end

app/controllers/login_controller.rb
# frozen_string_literal: true

class LoginController < ApplicationController
  before_action :must_be_signed_out, except: :delete

  def index
    @user = User.new
  end

  def create
    @user = User.sign_in(email: user_params[:email], password: user_params[:password])

    if @user
      sign_in(user: @user)
      redirect_to '/'
    else
      @user = User.new(email: user_params[:email], password: user_params[:password])
      @user.errors.add(:email, 'Email or password not found.')
      render :index
    end
  end

  def delete
    session[:user_id] = nil
    redirect_to login_path
  end

  def user_params
    params.require(:user).permit(:email, :password).to_h.symbolize_keys
  end
end

app/controllers/sign_up_controller.rb
# frozen_string_literal: true

class SignUpController < ApplicationController
  before_action :must_be_signed_out

  def index
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(user: @user)
      redirect_to '/'
    else
      render :index
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/controllers/timecard_controller.rb
# frozen_string_literal: true

class TimecardController < ApplicationController
  before_action :must_be_signed_in

  include ActionView::Helpers::DateHelper

  def index
    if active_timecard = current_user.active_timecard
      @timecard = active_timecard
      @msg = <<~MSG
        Hope you're having a good day.
        You started at #{active_timecard.clocked_in_at.to_formatted_s(:long_tz)},
        which was #{distance_of_time_in_words(active_timecard.clocked_in_at, Time.zone.now)} ago.
      MSG
      @submit_text = 'Clock out!'
    else
      @timecard = current_user.timecards.new
      @msg = 'Ready to start your day? ⏲️'
      @submit_text = 'Clock in!'
    end

    @timecards = current_user.timecards.complete.recent.first(10)
  end

  def create
    current_user.punch_clock!

    redirect_to '/'
  end

  def timecard_params
    params.require(:timecard).permit(:clock_in_at, :clock_out_at).to_h.symbolize_keys
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/admin/index.html.haml
.container
  .row
    %h1
      🙏, 🏅
      = "#{current_user.name}!"

  - if @timecards.any?
    .row
      %h3
        Timecards

      %p
        All time cards by recently updated
    .row
      %table.table.pt-6.mb-6
        %thead.thead-light
          %tr
            %th(scope="col") Name
            %th(scope="col") Start
            %th(scope="col") End
            %th(scope="col") Duration
        %tbody
          - @timecards.each do |timecard|
            %tr
              %td= timecard.user.name
              %td= timecard.clocked_in_at.to_formatted_s(:long_tz)
              %td
                - if timecard.clocked_out_at.present?
                  = timecard.clocked_out_at.to_formatted_s(:long_tz)
              %td
                - if timecard.clocked_out_at.present?
                  = distance_of_time_in_words(timecard.clocked_in_at, timecard.clocked_out_at)

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Punch Card"
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js'

  %body
    %nav.navbar.navbar-expand-lg.navbar-default
      %a.navbar-brand(href="/") Punch Card 👊
      - if current_user
        %span.nav-item.navbar-text.hide-sm
          = "👋, #{current_user.name}!"
        - if current_user.admin?
          %span.nav-item.navbar-text
            = link_to admin_path do
              Admin
        %span.nav-item.navbar-text
          = link_to logout_path do
            Sign Out
      - else
        %span.nav-item.navbar-text
          = link_to login_path do
            Sign In

    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield

app/views/login/index.html.haml
.container
  .row
    %h1
      Login to Punch Card 👊

    %p
      Keep track of your work hours

  .row
    = bootstrap_form_for(@user, url: login_path, method: :post) do |f|
      = f.email_field :email, label: 'Email', required: true
      = f.password_field :password, label: 'Password', required: true
      = f.submit 'Login', class: 'btn btn-primary'

  .row
    %p
      Don't have an account?
      = link_to 'Sign Up', sign_up_path, class: 'btn btn-primary'

app/views/sign_up/index.html.haml
.container
  .row
    %h1
      Sign Up for Punch Card

  .row
    = bootstrap_form_for(@user, url: sign_up_path, method: :post) do |f|
      = f.text_field :name, label: 'Name', required: true
      = f.email_field :email, label: 'Email', required: true
      = f.password_field :password, label: 'Password', required: true, help: 'Must be at least 6 characters'
      = f.submit 'Sign Up', class: 'btn btn-primary'

app/views/timecard/index.html.haml
.container
  .row
    %h1.mb-6
      = @msg

  .row
    = bootstrap_form_for(@timecard, url: timecard_punch_path, method: :post) do |f|
      = f.submit @submit_text, class: 'btn btn-primary'

  - if @timecards.any?
    .row
      %h3
        = "#{current_user.name}'s"
        most recent timecards

    .row
      %table.table.pt-6.mb-6
        %thead.thead-light
          %tr
            %th(scope="col") Start
            %th(scope="col") End
            %th(scope="col") Duration
        %tbody
          - @timecards.each do |timecard|
            %tr
              %td= timecard.clocked_in_at.to_formatted_s(:long_tz)
              %td
                - if timecard.clocked_out_at.present?
                  = timecard.clocked_out_at.to_formatted_s(:long_tz)
              %td
                - if timecard.clocked_out_at.present?
                  = distance_of_time_in_words(timecard.clocked_in_at, timecard.clocked_out_at)